apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-magento2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.36.136
    path: "/nfs/magen"

